updating github workflow
LeonardoMessias98/github_workflow_ci pull request #14
Opened 2021-12-15 20:02 UTC by LeonardoMessias98

2021-12-16 15:53 UTC, MatheusCampos-450 approved these changes

2021-12-16 15:56 UTC, justhenrique approved these changes

2021-12-16 15:58 UTC, MatheusCampos-450 approved these changes

2021-12-16 15:58 UTC, justhenrique approved these changes

2021-12-16 16:10 UTC, justhenrique approved these changes

2021-12-16 16:10 UTC, MatheusCampos-450 approved these changes

2021-12-16 17:21 UTC, MatheusCampos-450 requested changes

2021-12-16 17:21 UTC, MatheusCampos-450 commented on README.md
> +teste v1 2
essa letra poderia estar verde

2021-12-17 16:40 UTC, MatheusCampos-450 approved these changes

2021-12-17 17:46 UTC, closed without merging