Update README.md
LeonardoMessias98/github_workflow_ci pull request #72
Opened 2022-03-24 19:23 UTC by LeonardoMessias98

2022-03-24 19:26 UTC, MatheusCampos-450 requested changes, later dismissed

2022-03-24 19:26 UTC, MatheusCampos-450 commented on README.md
> +HOTFIX 3.0
`HOT FIX 300000.0`

2022-03-24 22:16 UTC, justhenrique commented on README.md
> +HOTFIX 3.0
Solicitação teste! 
```suggestion
HOTFIX 3.1
```

2022-03-25 17:04 UTC, LeoAccountForTests requested changes

2022-03-25 17:04 UTC, LeoAccountForTests commented on README.md
> +HOTFIX 3.0
Existe um erro

2022-03-25 17:18 UTC, MatheusCampos-450 requested changes

2022-03-25 17:18 UTC, MatheusCampos-450 commented on README.md
> +HOTFIX 3.0
Devia ser RROTFIX e não HOTFIX

2022-03-25 17:24 UTC, LeoAccountForTests approved these changes

2022-03-25 17:25 UTC, closed without merging